### PR TITLE
Pull Request for Set up 'Hello Microverse' Project

### PR DESCRIPTION
**Pull request by Fentahunn**
Description:
This pull request aims to set up the 'Hello Microverse' project, which serves as an introductory project for Microverse students. The project focuses on familiarizing students with the development environment and project structure.

The changes in this pull request include:

Project Structure: contains
Project structure and file setup
Basic HTML structure with 'Hello Microverse' greeting
CSS styling for visual enhancement
Updated project documentation in the README file
Thank you for your attention and feedback.

### CODE REVIEW

**Review by amon-cofie — CHANGES_REQUESTED** [review]
Hi @Fentahunn , 👋 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there! 💪 



## Highlights

🚀 You have a descriptive pull request summary
🚀 You have good commit messages
🚀 You properly installed linters and have no linter errors

## Required Changes ♻️

- [ ] You have done so well on this milestone 👍. You were able to install the linters locally and you added all the required files. You also added the node_modules directory and the test.md file to the ```.gitignore``` file and hence they were not pushed to the GitHub repository 💪. However, one of the requirements, and a very important one, was to add a README.md file uniform to the Microverse README template and personalize it to fit your project and the things you did in it. The README file serves as documentation for the project where users can go to find out more about your project and hence makes your repo professional 👍. I can see that you have a readme file and so I suggest that you adopt the Microverse README template and personalize it to suit your project. Here is a [link to the Microverse README template](https://github.com/microverseinc/readme-template). 

image


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Fentahunn** [comment]
This pull request contains :

- [x] Updated project documentation in the README file

**Review by osamaashraf6 — CHANGES_REQUESTED** [review]
Hi  @Fentahunn ☺️, 

Good job so far! 👏🥳
You have done well reaching this point of the milestone, but there are some issues that you still need to work on to go to the next project but you are almost there! 


you-are-near

## Highlights ✔️

- [x] Descriptive pull request title 👌
- [x] Good usage in correcting GitHub flow💯
- [x] Good adding the test and node modules at the gitignore 🚀

 ## Required Changes ♻️
- [ ] Kindly 😊 as stated by the previous reviewer use [the Microverse Readme template](https://github.com/microverseinc/readme-template) and make sure all the main sections present in yours and placeholders are replaced with your project and personal data. The only optional section is a FAQ. Please remove the template logo on the top, if you have one, you can replace it. This is crucial to have a professional and instructive repository. 👌


 

## Optional suggestions

- [ ]  Please 😊 consider using best practices when you write commit messages, they should be capitalized sentences in the imperative form, for example: "Fix bug at CSS file" instead of "Bug fixed in CSS file" ... etc 👍

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Fentahunn** [comment]
@osamaashraf6

- [ ] I am submitting this pull request to incorporate the revised Readme files in accordance with the specified Microverse Readme template.
- [ ] 

- [ ] This is the third request of me for this project only
- [ ] I need you feedback accordingly

**Review by Strangeal — CHANGES_REQUESTED** [review]
Hi @Fentahunn, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

Alt Text

 ## Required Changes ♻️
- [ ] Impressive work implementing the changes suggested but the previous reviewer, I see you have added the `README` but on the `main` branch instead of the branch you created the pull request on `(header)`.
   - Please make sure to commit the `README` to the `header` branch so that the previous reviewers can have access to it and make a review on it accordingly.
   
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Fentahunn** [comment]
changes in this pull request:

- [x] Move README to header branch

**Review by victorokoroji — APPROVED** [review]
Hi @Fentahunn , 

# ✔️   Status: APPROVED 🏆 🎉 🎊 

You have done a great job on this project, keep it up 👍 🥇. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
congratulations!  🎉💯🌟 

## Top highlight 🎯

- Requested changes implemented ✅ 



## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
